apiVersion: apps/v1
kind: Deployment
metadata:
  name: assesment1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assesment1
  template:
    metadata:
      labels:
        app: assesment1
    spec:
      containers:
      - name: assesment1
        image: prashant040/assesment1:latest
        ports:
        - containerPort: 3000
