apiVersion: v1
kind: Service
metadata:
  name: assesment-deployment
spec:
  selector:
    app: assesment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer